#!/bin/sh
### BEGIN INIT INFO
# Provides:		zapret
# Required-Start:	$local_fs $network
# Required-Stop:	$local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

SCRIPT=$(readlink -f "$0")
EXEDIR=$(dirname "$SCRIPT")
ZAPRET_BASE=$(readlink -f "$EXEDIR/../..")
. "$EXEDIR/functions"

NAME=zapret
DESC=anti-zapret

do_start()
{
    echo "Starting zapret daemon for Discord only..."
    /opt/zapret/nfq/nfqws --user=nobody \
        --dpi-desync-fwmark=0x40000000 \
        --qnum=200 \
        --dpi-desync=fake \
        --dpi-desync-ttl=3 \
        --dpi-desync-fooling=badsum \
        --hostspell=hoSt \
        --hostlist-domains=/opt/zapret/nfq/hosts.txt &

    [ "$INIT_APPLY_FW" != "1" ] || { zapret_apply_firewall; }
}

do_stop()
{
    zapret_stop_daemons
    [ "$INIT_APPLY_FW" != "1" ] || zapret_unapply_firewall
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		do_stop
		do_start
		;;
	start-fw|start_fw)
		zapret_apply_firewall
		;;
	stop-fw|stop_fw)
		zapret_unapply_firewall
		;;
	restart-fw|restart_fw)
		zapret_unapply_firewall
		zapret_apply_firewall
		;;
	start-daemons|start_daemons)
		do_start
		;;
	stop-daemons|stop_daemons)
		do_stop
		;;
	restart-daemons|restart_daemons)
		do_stop
		do_start
		;;
	reload-ifsets|reload_ifsets)	
		zapret_reload_ifsets
		;;
	list-ifsets|list_ifsets)	
		zapret_list_ifsets
		;;
	list-table|list_table)	
		zapret_list_table
		;;
  *)
	echo "Usage: $SCRIPT {start|stop|restart|start-fw|stop-fw|restart-fw|start-daemons|stop-daemons|restart-daemons|reload-ifsets|list-ifsets|list-table}" >&2
	exit 1
	;;
esac

exit 0
